package com.bawei.dianshangjinweek02.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.dianshangjinweek02.bean.CartlistBean;
import com.bawei.dianshangjinweek02.bean.OrderDataBean;

import com.bawei.dianshangjinweek02.dao.CartlistBeanDao;
import com.bawei.dianshangjinweek02.dao.OrderDataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartlistBeanDaoConfig;
    private final DaoConfig orderDataBeanDaoConfig;

    private final CartlistBeanDao cartlistBeanDao;
    private final OrderDataBeanDao orderDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartlistBeanDaoConfig = daoConfigMap.get(CartlistBeanDao.class).clone();
        cartlistBeanDaoConfig.initIdentityScope(type);

        orderDataBeanDaoConfig = daoConfigMap.get(OrderDataBeanDao.class).clone();
        orderDataBeanDaoConfig.initIdentityScope(type);

        cartlistBeanDao = new CartlistBeanDao(cartlistBeanDaoConfig, this);
        orderDataBeanDao = new OrderDataBeanDao(orderDataBeanDaoConfig, this);

        registerDao(CartlistBean.class, cartlistBeanDao);
        registerDao(OrderDataBean.class, orderDataBeanDao);
    }
    
    public void clear() {
        cartlistBeanDaoConfig.clearIdentityScope();
        orderDataBeanDaoConfig.clearIdentityScope();
    }

    public CartlistBeanDao getCartlistBeanDao() {
        return cartlistBeanDao;
    }

    public OrderDataBeanDao getOrderDataBeanDao() {
        return orderDataBeanDao;
    }

}
